name: Ubuntu Install and Command Run

on: [push]

jobs:

  ubuntu_install_and_run:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

      

    - name: Install Ubuntu

      uses: appleboy/setup-ubuntu@v2

      with:

        distribution: 'bionic'

        packages: 'git'

        

    - name: Run Command

      run: |

        echo "Hello, Ubuntu!"

        git --version
             git clone https://github.com/ajaysinghsati/devicetree.git device/qti/holi
             git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
             git clone https://github.com/LineageOS/android_prebuilts_extract-tools prebuilts/extract-tools
             git clone https://gitlab.com/android-dump/qti/holi.git
             cd device 
             ls 
             cd qti 
             ls
             cd holi
             ls 
    
             chmod u+x setup-makefiles.sh
             ./setup-makefiles.sh
             chmod u+x extract-files.sh
             ./extract-files.sh ~/holi
     
      

      - name: Installing Requirements
        run: |
             ls 
             cd vendor 
             ls
       
             ls 
     
             cd holi
             ls 
             cd qti 
             ls
             cd proprietary
      
             ls
             cd boot
             ls 
             cd ramdisk 
             ls 
             cd vendor 
             ls 
             cd lib64 
             ls

      
