name: DumprX

on:
  workflow_dispatch:
    
        description: 'Firmware Link'
        required: true



jobs:
  Firmware-Dump:
      runs-on: ubuntu-20.04

      steps:

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main 

      - name: Cloning DumprX
        run: |
             git clone --depth=1 https://github.com/neilchetty/Dumper-Scripts dumper
      - name: SettingUp SSH Keys
        run: |
        
             git clone https://gitlab.com/PixelOS-Devices/proprietary_vendor_oplus_camera.git -b 14.0 vendor/oplus/camera
             git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
             git clone https://github.com/LineageOS/android_prebuilts_extract-tools prebuilts/extract-tools
             git clone https://www.opencode.net/romdumprx/oneplus/OP535DL1.git
             cd vendor
             ls 
             cd oplus
             ls
             cd camera
             ls 
    
             chmod u+x setup-makefiles.sh
             ./setup-makefiles.sh
             chmod u+x extract-files.sh
             ./extract-files.sh ~/OP535DL1
     
      

      - name: Installing Requirements
        run: |
             ls 
             cd vendor 
             ls
       
             ls 
     
             cd holi
             ls 
             cd qti 
             ls
             cd proprietary
      
             ls
             cd boot
             ls 
             cd ramdisk 
             ls 
             cd vendor 
             ls 
             cd lib64 
             ls

      
